Step 1. Explore Dataset

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Housing.csv')

In [4]:
print("Dataset Shape")
df.shape

Dataset Shape

(545, 13)

In [5]:
print("First five rows:")
df.head()

First five rows:

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [6]:
print("column Names and types")
df.info()

column Names and types
<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 55.5 KB

In [7]:
print("Statistical Summary:")
df.describe()

Statistical Summary:

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [8]:
print("Missing Values:")
df.isnull().sum()

Missing Values:

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

Step 2. See Data Samples & Statistics

In [9]:
print("First 10 Rows")
print(df.head(10))

First 10 Rows
      price   area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000   7420         4          2        3      yes        no       no
1  12250000   8960         4          4        4      yes        no       no
2  12250000   9960         3          2        2      yes        no      yes
3  12215000   7500         4          2        2      yes        no      yes
4  11410000   7420         4          1        2      yes       yes      yes
5  10850000   7500         3          3        1      yes        no      yes
6  10150000   8580         4          3        4      yes        no       no
7  10150000  16200         5          3        2      yes        no       no
8   9870000   8100         4          1        2      yes       yes      yes
9   9800000   5750         3          2        4      yes       yes       no

  hotwaterheating airconditioning  parking prefarea furnishingstatus
0              no             yes        2      yes        furnished
1              no             yes        3       no        furnished
2              no              no        2      yes   semi-furnished
3              no             yes        3      yes        furnished
4              no             yes        2       no        furnished
5              no             yes        2      yes   semi-furnished
6              no             yes        2      yes   semi-furnished
7              no              no        0       no      unfurnished
8              no             yes        2      yes        furnished
9              no             yes        1      yes      unfurnished

In [10]:
print("Categorical Values:")
print(df['mainroad'].unique())
print(df['guestroom'].unique())
print(df['furnishingstatus'].unique())

Categorical Values:
<StringArray>
['yes', 'no']
Length: 2, dtype: str
<StringArray>
['no', 'yes']
Length: 2, dtype: str
<StringArray>
['furnished', 'semi-furnished', 'unfurnished']
Length: 3, dtype: str

Step 3. Convert Categorical to Numeric

In [4]:
yes_no_columns = ['mainroad', 'guestroom', "basement", 'hotwaterheating', 
                  'airconditioning', 'prefarea']
for col in yes_no_columns:
    df[col] = df[col].replace({'yes': 1, 'no': 0})

# Convert furnishingstatus only once.
if 'furnishingstatus' in df.columns:
    df = pd.get_dummies(df, columns=['furnishingstatus'], drop_first=True, dtype=int)

print("Updated Dataset")
df.head(10)

Updated Dataset

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1,0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0,0
5,10850000,7500,3,3,1,1,0,1,0,1,2,1,1,0
6,10150000,8580,4,3,4,1,0,0,0,1,2,1,1,0
7,10150000,16200,5,3,2,1,0,0,0,0,0,0,0,1
8,9870000,8100,4,1,2,1,1,1,0,1,2,1,0,0
9,9800000,5750,3,2,4,1,1,0,0,1,1,1,0,1

In [12]:
print("New Column")
df.columns.tolist()

New Column

['price',
 'area',
 'bedrooms',
 'bathrooms',
 'stories',
 'mainroad',
 'guestroom',
 'basement',
 'hotwaterheating',
 'airconditioning',
 'parking',
 'prefarea',
 'furnishingstatus_semi-furnished',
 'furnishingstatus_unfurnished']

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

Prepare X,Y

In [6]:
X = df.drop('price', axis=1) #all features except price
y = df['price']              #target price

print("Features (X) Shape: ", X.shape)
print("Target (y) Shape: ", y.shape)

print("Feature Columns:")
print(X.columns.tolist())

Features (X) Shape:  (545, 13)
Target (y) Shape:  (545,)
Feature Columns:
['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'parking', 'prefarea', 'furnishingstatus_semi-furnished', 'furnishingstatus_unfurnished']

Train Test Split 80/20

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42 )

print(f"Train set: {X_train.shape[0]} houses")
print(f"Test set: {X_test.shape[0]} houses")

Train set: 436 houses
Test set: 109 houses

Model 1: Linear Regression

In [8]:
print("Linear Regression")
model1 = LinearRegression()
model1.fit(X_train, y_train)
y_pred1 = model1.predict(X_test)

r2_1 = r2_score(y_test, y_pred1)
mae_1 = mean_absolute_error(y_test, y_pred1)
mse_1 = mean_squared_error(y_test, y_pred1)

print(f"   R^2 Score: {r2_1:.4f}")
print(f"   MAE: {mae_1:,.2f}")
print(f"   MSE: {mse_1:,.2f}")

Linear Regression
   R^2 Score: 0.6529
   MAE: 970,043.40
   MSE: 1,754,318,687,330.66

In [17]:
print("Decision Tree")
model2 = DecisionTreeRegressor(random_state=42)
model2.fit(X_train, y_train)
y_pred2 = model2.predict(X_test)

r2_2 = r2_score(y_test, y_pred2)
mae_2 = mean_absolute_error(y_test, y_pred2)
mse_2 = mean_squared_error(y_test, y_pred2)

print(f"   R^2 Score: {r2_1:.4f}")
print(f"   MAE: {mae_2:,.2f}")
print(f"   MSE: {mse_2:,.2f}")

Decision Tree
   R^2 Score: 0.6529
   MAE: 1,195,266.06
   MSE: 2,642,802,637,614.68

In [18]:
print("Random Forest")
model3 = RandomForestRegressor(n_estimators=100, random_state=42)
model3.fit(X_train, y_train)
y_pred3 = model3.predict(X_test)

r2_3 = r2_score(y_test, y_pred3)
mae_3 = mean_absolute_error(y_test, y_pred3)
mse_3 = mean_squared_error(y_test, y_pred3)

print(f"   R^2 Score: {r2_1:.4f}")
print(f"   MAE: {mae_3:,.2f}")
print(f"   MSE: {mse_3:,.2f}")

Random Forest
   R^2 Score: 0.6529
   MAE: 1,022,560.05
   MSE: 1,964,193,399,645.33

In [19]:
#Find Best model 
print("Model Comparison")

models = {
    'Linear Regression' : r2_1,
    'Decision Tree' : r2_2,
    'Random Forest' : r2_3
}

best_model = max(models, key=models.get)
print(f"Best MOdel: {best_model}")
print(f"R^2 Score: {models[best_model]:.4f}")

Model Comparison
Best MOdel: Linear Regression
R^2 Score: 0.6529

In [ ]:
# Using best model (Linear Regression)

# Example house values; replace these values for another prediction.
new_houses = pd.DataFrame({
    'area': [7420],
    'bedrooms': [4],
    'bathrooms': [2],
    'stories': [3],
    'mainroad': [1],
    'guestroom': [1],
    'basement': [1],
    'hotwaterheating': [1],
    'airconditioning': [1],
    'parking': [2],
    'prefarea': [1],
    'furnishingstatus_semi-furnished': [0],
    'furnishingstatus_unfurnished': [1]
})

# Make prediction
predictions = model1.predict(new_houses)

print("PRICE PREDICTION (Linear Regression)")

print(f"Predicted House Price: PKR {predictions[0]:,.0f}")

PRICE PREDICTION (Linear Regression)
Predicted House Price: PKR 8,861,142